Fixes and improvements to alerting system

diff --git a/bin/beep b/bin/beep
--- a/bin/beep
+++ b/bin/beep
@@ -3,6 +3,11 @@
 repetitions=$1
 [ -z "${repetitions}" ] && repetitions=1
 
+if [[ ! "${repetitions}" =~ '^[0-9]+$' ]]; then
+  echo "Error: First argument must be a number (the number of beeps to make)"
+  exit 1
+fi
+
 for i in $(seq ${repetitions}); do
   mplayer -noconsolecontrols -really-quiet ~/res/beep.mp3 &>/dev/null
   [ ${repetitions} -gt 1 ] && sleep 1
