bin/remote-screenshot: Improve debug & informational messages

diff --git a/bin/remote-screenshot b/bin/remote-screenshot
--- a/bin/remote-screenshot
+++ b/bin/remote-screenshot
@@ -9,6 +9,10 @@ outputfilepath=${tempfilepath}
 quiet=
 dry_run=
 
+YELLOW='\033[1;33m'
+RED='\033[0;31m'
+GREEN='\033[0;32m'
+NC='\033[0m'
 function run() {
   local cmd="$@"
   if [[ ! -z "${dry_run}" ]]; then
@@ -20,12 +24,17 @@ function run() {
 
 function warn() {
   [[ ! -z "${quiet}" ]] && return 0
-  echo "WARNING: $@" >&2
+  echo -e "${YELLOW}WARNING: $@${NC}" >&2
 }
 
 function error() {
   [[ ! -z "${quiet}" ]] && return 0
-  echo "ERROR: $@" >&2
+  echo -e "${RED}ERROR: $@${NC}" >&2
+}
+
+function success() {
+  [[ ! -z "${quiet}" ]] && return 0
+  echo -e "${GREEN}ERROR: $@${NC}" >&2
 }
 
 function print() {
@@ -52,10 +61,17 @@ EOF
 
 function print_parameters () {
 cat <<EOF
+
+Used parameters:
 user=${user}
 host=${host}
-display=${DISPLAY}
+display=${display}
 size=${size}
+tempfilepath=${tempfilepath}
+outputfilepath=${outputfilepath}
+quiet=${quiet}
+dry_run=${dry_run}
+
 EOF
 }
 
@@ -97,13 +113,15 @@ done
 
 if [[ $# -eq 0 ]]; then
     if [[ -z ${user} ]]; then
-        echo "User parameter is missing." >&2
+        error "User parameter is missing." >&2
+        print_parameters
         usage
         exit 1
     fi
 
     if [[ -z ${host} ]]; then
-        echo "Host parameter is missing." >&2
+        error "Host parameter is missing." >&2
+        print_parameters
         usage
         exit 1
     fi
@@ -134,6 +152,7 @@ fi
 
 if [[ $# -gt 0 ]]; then
     warn "Unused parameters $@" >&2
+    print_parameters >&2
 fi
 
 print "Taking screenshot on remote host."
@@ -148,7 +167,7 @@ if [[ ! $? -eq 0 ]]; then
     error "There was an error copying the remote screenshot file."
     exit 1
 else
-  print "Screenshot file found at: ${outputfilepath}"
+  success "Screenshot file found at: ${outputfilepath}"
 fi
 
 print "Cleaning up remote screenshot file"
